<?php
return array (
  10 => 
  array (
    'id' => '10',
    'catid' => '9',
    'typeid' => '0',
    'title' => '战略规划',
    'style' => '',
    'thumb' => 'http://mengzhicheng.com/uploadfile/2019/0731/20190731031229486.png',
    'keywords' => '',
    'description' => '在目前公司经营工作的基础上，合理制定今后几年发展目标，统筹安排，保证今后几年持续增长；要积极参加各项社会活动、广泛利用一切社会资源   ',
    'posids' => '0',
    'url' => 'http://mengzhicheng.com/index.php?m=content&c=index&a=show&catid=9&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1564557138',
    'updatetime' => '1564569545',
    'hitsid' => 'c-1-10',
    'views' => '17',
    'yesterdayviews' => '0',
    'dayviews' => '17',
    'weekviews' => '17',
    'monthviews' => '17',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '9',
    'typeid' => '0',
    'title' => '你见过大蛇吗',
    'style' => '',
    'thumb' => 'http://mengzhicheng.com/uploadfile/2019/0731/20190731030003820.png',
    'keywords' => '',
    'description' => '技术骨干：许剑波公司职务及社会职务描述：公司副总经理，协助总经理制定并实施企业战略、经营计划等政策方略，实现公司的经营管理目标及发   ',
    'posids' => '0',
    'url' => 'http://mengzhicheng.com/index.php?m=content&c=index&a=show&catid=9&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1564556271',
    'updatetime' => '1564566461',
    'hitsid' => 'c-1-9',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>